// Comprehensive list of villages in Gadag district + 3 neighbouring districts (Haveri, Koppal, Dharwad).
// Sourced from viewvillage.in (~1100 villages total). Used as autocomplete in patient registration.
//
// Receptionist can still add custom places via Settings → Default Location → Known Villages.
// Performance: ~30KB total string data, parsed once at app boot. Datalist with ~1100 options
// renders instantly in modern browsers — no perceptible slowdown.

export const KARNATAKA_PLACES: Record<string, string[]> = {
  Gadag: [
    'Adavisomapur','Adarakatti','Adrahalli','Akkigund','Alur','Alagilawad','Amaragatti','Amaragol','Amarapur',
    'Ankali','Antur','Arahunashi','Arahunasi','Arban','Arishinagodi','Ashakiran','Asundi','Asuti','Attikatti',
    'Abbigeri','Bagewadi','Balagod','Balaganur','Balajinagar','Balehosur','Banahatti','Bannikoppa','Baradur','Basapur',
    'Basarakod','Bastiban','Battur','Belaghatti','Beladhadi','Belahod','Belavanaki','Belleri','Bellatti','Benahal',
    'Benakanakoppa','Benachamatti','Bennihalli','Bentur','Betigeri','Bevinakatti','Bhairapur','Bharadi','Bhasalapur',
    'Bhavanur','Bheeranahatti','Bhopalapur','Bidarahalli','Bidnal','Bijjur','Binkadakatti','Bommasagar','Brahmandapur',
    'Budihal','Byalawadgi','Chabbi','Channapattana','Chavadal','Chikkahandigol','Chikkanargund','Chikkasavanur',
    'Chikkawaddatti','Chikkmannur','Chikkoppa','Chickalagundi','Chilzeri','Chinchalli','Churchihal','Da Sa Ramenahalli',
    'Dambal','Dandapur','Desai Ban','Devihal','Dindur','Doddur','Doni','Dundur','Dyamhunashi','Eklasapur',
    'Futagao Badni','Gadag','Gadgoli','Gangapur','Gavarawad','Gogeri','Gojanur','Goudageri','Govanakoppa','Govanal',
    'Guddadapur','Guddadbudihal','Gujmagadi','Gulaganjikoppa','Gulaguli','Gulagundi','Gumgol','Gurlakatti','Hadagali',
    'Hadali','Haitapur','Halakeri','Halligudi','Hallikeri','Hammigi','Hanganakatti','Haradagatti','Harogeri','Harti',
    'Harlapur','Hatalageri','Hebbal','Hesarur','Hire Mallapur','Hirealagundi','Hirehal','Hirehandigol','Hiremannur',
    'Hirekoppa','Hirewaddatti','Holalapur','Hole Hadagali','Hole Mannur','Holealur','Hombal','Honnapur','Honniganur',
    'Hosahalli','Hosalli','Hosur','Huilgol','Hulgeriban','Hulkoti','Hullur','Hunagundi','Hunashikatti','Itagi',
    'Jagapur','Jakkali','Jalashankarnagar','Jalligeri','Jantli','Jigalur','Jigeri','Jyalawadgi','Kabalayata Katti',
    'Kadadi','Kadakol','Kadampur','Kakkur','Kalakapur','Kalakeri','Kalasapur','Kalkeri','Kalliganur','Kallaganur',
    'Kallapur','Kallur','Kanakawad','Kanakikop','Kanaginahal','Kanavi','Kappali','Kappatagiri','Karamadi','Karkikatti',
    'Kaujageri','Kelur','Kerihalli','Khanapur','Kiritageri','Kodaganur','Koganur','Kokkargundi','Konchigeri','Kondikoppa',
    'Konnur','Korlhalli','Kotabal','Kotumachagi','Krishanpura','Kundralli','Kuntoji','Kurahatti','Kurlageri','Kurtakoti',
    'Kurudagi','Kurugovinakoppa','Kuruvinakoppa','Kusalapur','Lakhamapur','Lakkalakatti','Lakkundi','Lakshmeshwar',
    'Lingadhal','Machenahalli','Madaganur','Madagunaki','Madalagiri','Madhalli','Magadi','Mahalingeshwarapur','Maktumpur',
    'Majjur','Malasamudra','Malawad','Mallapur','Mallikarjunapura','Maranabasari','Maruthinagar','Matarangi','Megur',
    'Melmath','Menasigi','Meundi','Mudenagudi','Muganur','Mugali','Mulgund','Mundargi','Mundawad','Muradi','Mushigeri',
    'Mustikoppa','Myakalzeri','Nabhapur','Nadigatti','Nagaral','Nagaramaduvu','Nagarahalli','Nagarashikoppa','Nagasamudra',
    'Nagavi','Nagendragad','Nainapur','Narasapur','Narayanapura','Naregalla','Nargund','Nave Bhavanur','Nellur','Nelogal',
    'Neelagund','Neeralagi','Nidagundi','Pandurangapur','Papanashi','Parasapur','Peth','Pethaban','Purthageri',
    'Radder Naganur','Rajur','Ramageri','Ramenahalli','Rampur','Ranatur','Rona','Rudrapur','Sambhapur','Sandigavad',
    'Sankadal','Sarjapur','Sasarwad','Savadi','Seethalahari','Sevanagar','Sevalalnagar','Shagoti','Shantagiri',
    'Sheernahalli','Shettikeri','Shigli','Shingatalur','Shingatarayanakeri','Shirahatti','Shirol','Shirur','Shirunja',
    'Shivajinagar','Shyabala','Siddapur','Siddarameshwara Nagar','Sogiwal','Somanakatti','Somapur','Soratur','Sudi',
    'Sugnalli','Suranagi','Surkod','Suvarnagiri','Tallihal','Tambragundi','Tangod','Tarikoppa','Tegginabhavanur','Timmapur',
    'Tippapur','Tolali','Ullatti','Unachageri','Undenahalli','Vadegol','Varavi','Vasan','Veerapur','Venkatapur',
    'Venkateshnagar','Virapapur','Vithalapur','Wadavi','Wadeyar Mallapur','Yalavatti','Yalishirur','Yallapur','Yarebeleri',
    'Yattinahalli','Yavagala','Yerekurubanal',
  ],
  Haveri: [
    'Adur','Agadi','Agasanhalli','Agasanamatti','Airani','Ajagundikoppa','Akki Alur','Akkivalli','Akkur','Alalageri',
    'Aladakatti','Aladageri','Aldakatti','Allipura','Allapur','Anaji','Angaragatti','Ankasapur','Antaravalli','Anur',
    'Apinakoppa','Arabagonda','Aralihalli','Aralikatti','Araleshwar','Arashinguppi','Aregoppa','Aregoppaa','Arelakmapur',
    'Arikatti','Asundi','Attigeri','Avalagerikoppa','Babapur','Badabasapur','Badamalli','Badamgatti','Badasangapur',
    'Bagewadi','Baichavalli','Bailwal','Bailmadapura','Balambeed','Balambid','Balihalli','Balur','Bannihalli','Bannihatti',
    'Bardur','Basanal','Basapur','Basapur (m) Adur','Basapur (m) Nidasangi','Basarihalli','Basavanakatti','Basavankoppa',
    'Battikoppa','Beeranakoppa','Belakeri','Belavanaki','Belavigi','Belavatti','Belagalapeth','Belur','Bellur','Benakanahalli',
    'Benchihalli','Betakerur','Bevinahalli','Bharadi','Bhairapur','Bhingapur','Bhogavi','Bidarakoppa','Bidaragaddi',
    'Billahalli','Bisalahalli','Bommanahalli','Bommanakatti','Budapanahalli','Budagatti','Buradikatti','Bullapur',
    'Byadgi','Byagawadi','Byalawadgi','Byathanal','Chalageri','Challal','Channalli','Channapur','Channur','Chandapur',
    'Chandragiri','Chapparadahalli','Chatnalli','Chattra','Cheeranahalli','Chikka Aralahalli','Chikkabasur','Chikkalingadahalli',
    'Chikka Kuravatti','Chikka Mattur','Chikkabbar','Chikkaboodihal','Chikkahullal','Chikkalli','Chikkamaganur','Chikkamaralihalli',
    'Chikkamoraba','Chikkamugadur','Chikkanaji','Chikkanshi','Chikkayadachi','Chikkeri','Chikkounshi Hosur','Chillur',
    'Chilzeri','Chinnamulagund','Chinnikatti','Chogachikoppa','Chowdala','Choudayya Danapur','Dammalli','Danoagihalli',
    'Dasanakoppa','Dasharatkoppa','Devagiri','Devagiri Yellapur','Devihosur','Dhulikoppa','Dhupadahalli','Didagur',
    'Divagihalli','Doddagubbi','Dolleshwar','Dombaramattur','Dommanala','Dudihalli','Dummihal','Dyamankoppa','Eklasapur',
    'Fakir Nandihalli','Fattepur','Gadegundiyellapur','Gadiyankanahalli','Galaginakatti','Galaganath','Ganajur','Gangaikoppa',
    'Gangapur','Gazipur','Gejjihalli','Ghalapuji','Girishinkoppa','Godachikonda','Godihal','Gondi','Gonala','Gotagodi',
    'Gourapur','Gudisalkoppa','Gudur','Gudagudi','Guddada Mallapur','Guddadabevinahalli','Guddadachannapur','Guddadahosahalli',
    'Guddadamadapur','Guddad Mattihalli','Guddadanveri','Guddaguddapur','Gummanahalli','Gundagatti','Gundenahalli','Gundur',
    'Gururayapatna','Guttal','Hadagali','Hadrihalli','Hade','Halagi','Halegejjihalli','Hale Gungaragoppa','Hale Kamanhalli',
    'Halekoti','Halekunta','Halenidanegilu','Halagi','Haleritti','Haleshigihalli','Haleveerapur','Haligeri','Hallibail',
    'Hallibail Vaddarageri','Halliyal','Hallur','Hanamapur','Hanamasagar','Hanmanhalli','Hanumanahalli','Hanumanakoppa',
    'Hanumapur','Handihal','Handiganur','Haralahalli','Haranagiri','Harlakoppa','Harogoppa','Harvi','Hasanabadi',
    'Hatti','Hattimattur','Haunsabhavi','Haunshi','Havanagi','Havanur','Haveri','Hediyal','Hedigonda','Heeladahalli',
    'Heerur Gollarabidar','Herur','Hesarur','Hirebasur','Hirebudihal','Hirebidari','Hirehalli','Hirekanagi','Hirekonati',
    'Hirekounshi','Hirelingadahalli','Hiremaganur','Hiremaralihalli','Hiremattihalli','Hiremoraba','Hiremugadur','Hireanaji',
    'Hirebasur','Hirenandihalli','Hirur','Holabikonda','Hole Hadagali','Hole Mannur','Holealur','Hombardi','Hombli',
    'Honikop','Honkan','Honnatti','Honnapur','Hosahalli','Hosakatti','Hosakittur','Hosalli','Hosa Gungaragoppa',
    'Hosa Nidanegilu','Hosaritti','Hosaveerapur','Hospet','Hotanhalli','Huda','Hulagaddi','Hulaginakoppa','Hulaginahalli',
    'Hulihalli','Hulikatti','Hullatti','Hulyala','Hunashettikioppa','Hunashikatti','Hunashikatti','Huralikuppi','Huvinshigli',
    'Ibrahimpur','Ichala Yellapur','Ichangi','Ijarilakamapura','Ingalagondi','Itagi','Jakkanaikankoppa','Jallapur',
    'Janagundikoppa','Janginakoppa','Jangamanakop','Jekenakatti','Jogihalli','Jokanala','Joisaraharalahalli','Jyavalli',
    'Kabbur','Kachavi','Kadakola','Kadamanahalli','Kadaramandalagi','Kadashettihalli','Kadur','Kaginelli','Kajjari',
    'Kakol','Kalagonda','Kalakeri Tanda','Kalalkond','Kalasur','Kalguddi','Kallapur','Kallihal','Kalledevar','Kaliwal',
    'Kalmadavu','Kalkeri','Kalvekallapur','Kalveyellapur','Kalvihalli','Kamadod','Kamanahalli','Kamanahalli Kaloni',
    'Kamanahalli Tanda','Kamal Bangadi Timmapur','Kamalapur','Kanakapur','Kanavalli','Kancharagatti','Kanchinegalur','Kanneshwar',
    'Karadagi','Karekyatanahalli Tanda','Karekyathanahalli','Kargi','Kargudri','Karjagi','Karur','Kasambi','Katenahalli',
    'Kavalikoppa','Kawalettu','Kelavarkoppa','Kenchayikoppa','Kerikop','Kerimallapur','Kerimattihalli','Kerawadi','Kesaralli',
    'Khanderayanahalli','Khurda Veerapura','Khurdha Kodihalli','Khandibagur','Kirageri','Kirwadi','Kod','Kodabal','Kodamaggi',
    'Kodihalli','Kodiyal','Kodiyellapur','Kollapur','Kolur','Konana Tambigi','Konanatali','Konanatambigi','Konankoppa',
    'Kondoji','Kondogivadageri','Kooli','Koppagondankop','Kopparsikoppa','Koradur','Kotihal','Krishnapur','Kudal','Kudapali',
    'Kudrihal','Kunabev','Kunchur','Kunimellihalli','Kuntanhosahalli','Kuppelur','Kurabagonda','Kurubaramallur','Kuragund',
    'Kulenur','Kummur','Kusagatti','Kusagur','Kusnur','Kyasanur','Kyatanakeri','Lakamaji Koppa','Lakmapur','Laxmapur',
    'Laxmipur','Lingadalli','Lingadevarakoppa','Maagod','Maharajpet','Madapur','Madlur','Maidur','Makari','Makanur',
    'Makarvalli','Malagi','Malagund','Malanaikanahalli','Malakanahalli','Malapur','Malligar','Mallur','Mannangi','Mannur',
    'Manakur','Mantagani','Mantrodi','Maradur','Maranbeed','Marol','Maruthipura','Masanagi','Masankatti','Masur','Mattihalli',
    'Mavakoppa','Mavinatop','Mavoor','Medleri','Medur','Megur','Melligatti','Melmuri','Menashinahal','Meundi','Motebennur',
    'Mudenur','Mudur','Mulathalli','Muddinakoppa','Muttur','Mustur','Naganur','Nagalapur','Nagarahalli','Nagawand',
    'Naikerur','Najikalakamapur','Nalawagal','Nandihalli','Naregal','Negavanigi','Neeralgi','Neeralagi','Negavanigi',
    'Neglur','Nelogal','Nellibeed','Nellikoppa','Neralgi','Neshwi','Nidagundi','Nittur','Nitaginakoppa','Nitapalli',
    'Nukapur','Nukapur','Padmavathipur','Paramawadi','Parvata Shidgeri','Puradakeri','Purakondikoppa','Rajeevgram','Rajiv Nagar',
    'Ramapur','Ramatirta','Ramathirtha','Ramgondanahalli','Rampura','Ranebennura','Rathnapur','Rattihalli','Sagarvalli',
    'Sammasgi','Sandigavad','Sankrikoppa','Sannagubbi','Sannasangapur','Sarvanda','Satenhalli','Satenahalli','Satagihalli',
    'Savasgi','Savikeri','Savanura','Savoor','Sevalal','Sevalalpur','Sevanagar','Shankaranahalli','Shankripura','Shanakaranahalli',
    'Shevalalpur','Sheegihalli','Sheshagiri','Shiddedevapura','Shidaganahal','Shidenur','Shidlapur','Shiggaon','Shigganva',
    'Shimoga','Shingapur','Shiramanakoppa','Shirgoda','Shirhatti','Shiramangi','Shirmapur','Shirol','Shirur','Shirur Tanda',
    'Shirhatti','Shitikonda','Shivajinagar','Shivanagar','Shivapur','Shivapura','Shyabala','Shyadambi','Shyadaguppi',
    'Sidaganahal','Siddapur','Siddapura','Sidlabhavi','Sirgumpi','Sivajipur','Somanahalli','Somasagara','Somapur','Somlapur',
    'Sringeri','Sudambi','Sugnalli','Sutakoti','Sunkapura','Sunakalbidari','Surleshwar','Tadakanahalli','Tadas','Talkere',
    'Tarikoppa','Tavargoppa','Taredahalli','Tegginabhavanur','Teredhalli','Thimmapur','Thippalapur','Thirumalapura','Timalapur',
    'Timmapur','Timmenahalli','Tilavalli','Tippaikoppa','Tirumaladevarakoppa','Tolali','Totaganti','Totadayellapur','Tumarikoppa',
    'Tumminakatti','Udagatti','Ujanipur','Ukkund','Uppanshi','Vadenapur','Vadnikoppa','Varadahalli','Varavi','Veerapur',
    'Veerapura','Walageri','Walaweri','Wadavi','Wadeyar Mallapur','Wadenapur','Wardi','Wasan','Yadagod','Yakalasapur',
    'Yalabadigi','Yalawadahalli','Yaliwal','Yallapur','Yallur','Yamiganur','Yarebeleri','Yattinahalli','Yelagachi','Yellapur',
    'Yelavigi','Yenntinahalli','Yennihosahalli','Yerekuppi','Yethinahalli',
  ],
  Koppal: [
    'Achalapur','Acharnarsapur','Achartimmapur','Adapura','Adavisomapur','Adoor','Advibhavi','Advihalli','Agalkera',
    'Agoli','Akalkumpi','Akkeri','Akkur','Allanagar','Allipur','Alwandi','Amarapur','Amarapura','Anegundi','Anjanhalli',
    'Anjuri Camp','Antarthana','Anugondana Koppa','Arhal','Arishinakerithanda','Arkeri','Arlahalli','Arsinkera','Arunodaya Camp',
    'Attivatti','Ayodhya','Bachinhal','Badimnhal','Baglapura','Bahaddurbandi','Bailakampur','Balapur','Balgera','Balutagi',
    'Ballutagi Tanda','Ballutgi','Bandi','Bandihal','Bandiharlapur','Bandikunta','Banderhal','Bannikoppa','Bankapur','Banhatti',
    'Bapireddi Camp','Bargur','Basapattana','Basapur','Basarihal','Basavanna Camp','Basavannaa Camp','Basavankoppa','Basaveshwar Camp',
    'Bassapur','Basvandurg','Battarnarsapur','Batterhanchnal','Bedwatti','Beelagi','Belavinal','Belgatti','Bellur','Belur',
    'Benakal','Benkanhal','Bennur','Benchamatti','Bevinhal','Bevoor','Bhairapur','Bhairapura','Bhairnaikanhalli','Bhanapur',
    'Bhatpanhalli','Bhevinagar','Bhimanur','Bhingikoppa','Bijakal','Bikanhalli','Bilebhavi','Bilekal','Binhal','Biraldinni',
    'Bisarhalli','Bisnhal','Bochanhalli','Bomchihal','Bommanhal','Bommasagara','Boon Koppa','Budakunti','Budihal','Budgumpi',
    'Budugumpa','Budur','Budsettinhal','Bukkanhatti','Bullabhai Camp','Bullapur','Bunhatti','Byalihal','Chalgera','Challari',
    'Challur','Chamalapura','Chandragiri','Chanpanhalli','Chendinhal','Chendoor','Chickgonnagar','Chickmukrtinhal','Chicknandihal',
    'Chickrampur','Chickwankal Kunta','Chika Mannapur','Chikboganhal','Chikbeedinhalu','Chikbendigeri','Chikbommanhal','Chikbannigol',
    'Chikkasankandi','Chikka Arlihalli','Chikka Benkal','Chikka Dankankal','Chikka Jantkal','Chikka Khed','Chikka Madinal',
    'Chikka Wadderkal','Chikkatamminal','Chiken Koppa','Chikmyageri','Chikoppa','Chikkoppa Tanda','Chiksindogi','Chiksulikeri',
    'Chilkmukki','Chilwadgi','Chitapur','Choudapur','Chukankal','Dadegal','Daggi Camp','Dammur','Danapur','Dasanhal',
    'Devlapur','Dhangaldoddi','Dombarhalli','Donnegudda','Dotihal','Dyampur','Eachanhal','Eliganoor','Gaddi','Gabbur',
    'Gadchinti','Gandhal','Ganganhal','Gangawati','Gavarhal','Gedigera','G.jarkunti','Garjanhal','Ghatreddihal','Ginigera',
    'G.virapur','Godinal','Gonal','Gondbal','Gonhal','Gorbihal','Gorelekoppa','Gorvarbenchamatti','Gorvihanchinal','Gosaldoddi',
    'Gotagi','Gouripur','Gudadhanamsagar','Gudadhurkal','Gudadur','Guddadadevalapur','Guddadur','Guddalakampur','Gudigera',
    'Gudur','Guldahalli','Guldal','Gule','Gumgeri','Gundur','Gunhalli','Gunhalu','Guntamadu','Guttur','Habalkatti',
    'Hadagli','Hagaldhal','Hagedal','Hagedhal','Hale Juratagi','Hale Kanakapur','Halekanakapur','Halekunta','Hale Ningapur',
    'Halgera','Halsamudra','Halwagali','Halwarti','Hampasadurg','Hanamageri','Hanamsagar','Hanchinhal','Handral','Hanmanhal',
    'Hanmanhalli','Hanmanhatti','Hanmapur','Hanumanahalli','Hanwal','Harishankerbandi','Hasgal','Hatti','Hebbal','Hemagudda',
    'Herur','Hesrur','H.g Ramulu Nagar','Hire Arlihalli','Hire Benkal','Hire Bommanhal','Hire Dankankal','Hire Khed',
    'Hire Madinal','Hire Waddarkal','Hire Wankal Kunta','Hireboganhal','Hirebannigol','Hirebeedinhalu','Hirebommanhal',
    'Hiregonnagar','Hirekhasankandi','Hiremannapur','Hiremukartihal','Hiremyageri','Hirenandihal','Hiresindogi','Hiresulikeri',
    'Hiretemminhal','Hitnal','Holemudlapur','Homminhal','Hongaddi','Honhunashi','Honmatti','Horthatanhal','Hosakanakapur',
    'Hosakera','Hosalingapur','Hosalli','Hoshalli','Hosagudda','Hosur','Hosur(k)','Huchnoor','Hulgi','Hulegudda','Hulgera',
    'Hulihyder','Huliyapur','Hulkihal','Hulsanhatti','Hulsegeri','Hunashalli','Hunkuntiakkapur','Hunsihal','Hussainpur','Huvinhal',
    'Hyati','Hydernagar','Idlapur','Indargi','Ingaldal','Irkalgada','Itagi','Jabbalgudda','Jagir Gadadur','Jalihal',
    'Jalihuda','Jamapur','Jangamarkalgudi','Jantkal','Jeeral','Jeeralkalgudi','Jhulkatti','Jinnapur','Jinnapurthanda',
    'Jinnapurcikkathanda','Jirala Kalgudi','Jumlapur','Juratgi','Kabbargi','Kadar Halli','Kadbalkatti','Kadekoppa','Kadival',
    'Kadoor','Kakkargol','Kakkihalli','Kalak Bandi','Kalalbandi','Kalbhavi','Kalgonhal','Kalkera','Kalkeri','Kalmalli',
    'Kalhalli','Kalliganur','Kallur','Kaltavargera','Kamanur','Kampasagar','Kampli','Kanakapur','Kanakapura','Kanakgiri',
    'Kandakur','Kanhal','Kankoppa','Kannermadu','Kardigudda','Kardona','Karatgi','Karkihalli','Karmudi','Katarkigudlanur',
    'Katapur','Katgihalli','Katral','Katrahalli','Kavalkere','Kawaloor','Kerihalli','Kesakihanchnal','Kesarhatti','Kesoor',
    'Keslapur','Khanapur','Kidadhal','Kidadur','Kilarhatti','Kinhal','Kodadhal','Kodatgeri','Kolihal','Kolur','Komlapur',
    'Konapur','Konasagar','Koppal','Kordakera','Kottankal','K.parsapur','Krishnapur','Kudgunti','Kudloor','Kudri Kotgi',
    'Kudri Moti','Kuknoor','Kukanpalli','Kumar Ramankunta','Kumblavati','Kunikera','Kunikera Tanda','Kuntoji','Kurbanhal',
    'Kushtagi','Kutganhalli','Kyadiguppa','Kyarihal','Lachankera','Lakmangule','Lagalur','Lakmapur','Layadhunsi','Lebgera',
    'Lingadahalli','Lingadhalli','Madalgatti','Madikera','Madinur','Madlur','Madnal','Madapur','Mainahalli','Majarenarasapura',
    'Makkahalli','Malaksamudra','Malgitti','Malkanmardi','Malkapur','Malligwad','Mandalmari','Mandalgeri','Mangalapur',
    'Mangalore','Manedhal','Mannapur','Mankalkeri','Mannerhal','Maranhal','Markat','Mataldinni','Marli','Markumbi','Masabhanchinhal',
    'Masbinkurbanhal','Mastkatti','Mathur','Matur','Matrangi','Mavinitagi','Mayadhunsi','Megur','Mellikeri','Mensageri',
    'Mettinhal','Metgal','Mittalkod','Miyapur','Mohammad Nagar','Moranhalli','Muddaballi','Muddalgundi','Mudenoor','Mudhol',
    'Mudhotagi','Mudlapur','Mugnoor','Mukkumpi','Mukthagudadur','Mundaragi','Munirabad','Muradi Thanda','Murdi','Murlapur',
    'Muslapur','Muthalu','Mustur','Myadardokki','Myadneri','Mylapur','Naglapur','Nageshanahalli','Nagarhal','Nagarhalli',
    'Nandapur','Nandihalli','Narayanpet','Naregal','Narinhal','Narsapur','Narsipur','Navali','Nawalhalli','Neeralgi',
    'Nelgeri','Nerebenchi','Nidsesi','Nilogal','Nilogipur','Ningapur','Ningalbandi','Nirlakoppa','Nittali','N.jarkunti',
    'Obalbanda','Ojanhalli','Pannapur','Parapur','Paramanhatti','Parasapur','Pattalchinti','Pragati Nagar','Pura','Puratageri',
    'Putakmari','Raghunathanhalli','Rajapur','Rajarampet','Rajoor','Ramdurg','Rampur','Ratnagiri','Rudrapura','Ryavanki',
    'Ryawanki','Salbhavi','Sanapur','Sangapur','Sanganhal','Sankanhal','Sankanur','Sasvihal','Sebankatti','Shadalgera',
    'Shahapur','Shakapur','Shalignoor','Shakthinagar','Shevalalpur','Shevalalpuru','Shirabadgi','Shivapur','Sidaganhalli',
    'Siddapur','Sidlabhavi','Sidnekoppa','Singanhal','Sirgumpi','Singangund','Sirur','Sirwar','Sompur','Somanhal','Somsagara',
    'Sriramanagar','Sulekal','Sulthanpur','Surapgatti','Taad Kanakapur','Tadkal','Talbal','Talkere','Tallihalli','Talugeri',
    'Talur','Tambragundi','Tankankal','Taralkatti','Tarikoppa','Tatakunti','Tawargera','Teggihal','Teggihalli','Tekkalki',
    'Temba','Tengunti','Tigari','Timmanhatti','Timmapur','Tippanhal','Tipparasanhalu','Tirmalapur','Tondihal','Tonasihal Thanda',
    'Tonsihal','Topalkatti','Tuggaldoni','Tumrikoppa','Tumurguddi','Turkanur','Uchalkunta','Uddihal','Udamkal','Ulenoor',
    'Umlirampur','Uplapur','Uppaldinni','Upparbasapur','Usalkoppa','Vakkandurga','Vajra Bandi','Vanageri','Vangera','Vanjabhavi',
    'Varankhed','Varikal','Veerapur','Venkatapur','Venkatagiri','Venkateshwaranagar','Vipra','Virpapur','Virupapur','Virupapuragaddi',
    'Vithalapur','Vithlapur','Wadparvi','Wanballary','Wadganhal','Wadki','Watparvi','Yadiapur','Yapaldinni','Yarihanchinal',
    'Yedoni','Yelamgera','Yelbunchi','Yelburga','Yelburthi','Yemmigudda','Yerdona','Yerigeri','Yerigonhal','Yettinhatti',
    'Zhoolkatti','Zhoolkunti','Zhunjalkoppa',
  ],
  Dharwad: [
    'Dharwad','Hubballi','Kalghatgi','Kundgol','Navalgund','Annigeri','Alnavar','Kolivad','Mishrikoti','Saunshi',
    'Garag','Yaragatti','Marewad','Tegur','Tadakod','Hebsur','Mansur','Uppinabetageri','Amargol',
  ],
};

// Flat de-duplicated list (case-insensitive on dedupe), ready to feed a <datalist>
export const ALL_NEARBY_PLACES: string[] = (() => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const district of Object.keys(KARNATAKA_PLACES)) {
    for (const p of KARNATAKA_PLACES[district]) {
      const k = p.trim().toLowerCase();
      if (!seen.has(k)) { seen.add(k); out.push(p); }
    }
  }
  return out;
})();

// Districts of Karnataka relevant for the suggester.
export const KARNATAKA_DISTRICTS: string[] = [
  'Bagalkot', 'Ballari', 'Belagavi', 'Bengaluru Rural', 'Bengaluru Urban', 'Bidar',
  'Chamarajanagar', 'Chikkaballapur', 'Chikkamagaluru', 'Chitradurga', 'Dakshina Kannada',
  'Davanagere', 'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kalaburagi', 'Kodagu', 'Kolar',
  'Koppal', 'Mandya', 'Mysuru', 'Raichur', 'Ramanagara', 'Shivamogga', 'Tumakuru',
  'Udupi', 'Uttara Kannada', 'Vijayanagara', 'Vijayapura', 'Yadgir',
];
