// Common professions for clinic patients (small-town India focus).
// Used as autocomplete suggestions during patient registration.
// Sorted by rough frequency in mind for typical OPD patient mix.
export const TOP_PROFESSIONS: string[] = [
  'Farmer',
  'Housewife',
  'Student',
  'Retired',
  'Daily wage labourer',
  'Shopkeeper',
  'Driver',
  'Teacher',
  'Auto driver',
  'Construction worker',
  'Tailor',
  'Government employee',
  'Private employee',
  'Self employed',
  'Unemployed',
  'Businessman',
  'Mechanic',
  'Carpenter',
  'Electrician',
  'Plumber',
  'Painter',
  'Welder',
  'Cook',
  'Domestic help',
  'Watchman / Security guard',
  'Sweeper',
  'Cleaner',
  'Dairy worker',
  'Cattle / Livestock farmer',
  'Agricultural labourer',
  'Vegetable vendor',
  'Fruit vendor',
  'Flower vendor',
  'Fish vendor',
  'Hotel worker',
  'Waiter',
  'Receptionist',
  'Hairdresser / Barber',
  'Beautician',
  'Tea / Coffee shop owner',
  'Petrol pump attendant',
  'Truck driver',
  'Bus driver',
  'Cab driver',
  'Delivery boy',
  'Courier',
  'Office clerk',
  'Accountant',
  'Bank employee',
  'Police constable',
  'Postal worker',
  'Railway employee',
  'Nurse',
  'Pharmacist',
  'Doctor',
  'Lab technician',
  'Compounder',
  'ASHA worker',
  'Anganwadi worker',
  'Lawyer',
  'Engineer',
  'IT professional',
  'Software developer',
  'Sales executive',
  'Marketing executive',
  'Insurance agent',
  'Real estate agent',
  'Contractor',
  'Architect',
  'Hotelier',
  'Caterer',
  'Photographer',
  'Videographer',
  'Journalist',
  'Reporter',
  'Tutor',
  'Coach',
  'Yoga instructor',
  'Priest / Pujari',
  'Imam',
  'Pastor',
  'Tailor master',
  'Goldsmith',
  'Blacksmith',
  'Cobbler',
  'Potter',
  'Weaver',
  'Mason',
  'Plumber',
  'Sanitation worker',
  'Garbage collector',
  'Gardener / Mali',
  'Farm hand',
  'Beedi worker',
  'Mill worker',
  'Factory worker',
  'Garment worker',
  'Sugar mill worker',
  'Textile worker',
  'Office assistant',
  'Peon',
  'Watchman',
  'Helper',
  'Apprentice',
  'Intern',
  'Other',
];
